// BOOKING
export const POST_BOOKING_FORM = "POST_BOOKING_FORM";
export const POST_BOOKING_FORM_SUCCESS = "POST_BOOKING_FORM_SUCCESS";
export const POST_BOOKING_FORM_FAILED = "POST_BOOKING_FORM_FAIELD";

